[workspace]
resolver = "2"
members = [
    "nanuak-schema",
    "nanuak-youtube-takeout-ingest"
]

[workspace.dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.23", features = ["derive"] }
color-eyre = "0.6.3"
diesel = { version = "2.0", features = ["postgres"] }
eyre = "0.6.12"
nanuak-schema = { path = "nanuak-schema" }
serde = {version="1.0.215", features=["derive"]}
serde_json = "1.0.133"
tokio = { version = "1.42.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
url = "2.5.4"
