[package]
name = "nanuak-schema"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { workspace = true }
chrono = { workspace = true }
pgvector = { workspace = true }
diesel_full_text_search = { workspace = true }
