# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema.youtube]
file = "src/youtube_schema.rs"
schema = "youtube"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
import_types = ["diesel::sql_types::*", "pgvector::sql_types::*","diesel_full_text_search::Tsvector"]
generate_missing_sql_type_definitions = false

[migrations_directory]
dir = "G:\\repos\\Nanuak\\nanuak-schema\\migrations"
