[package]
name = "nanuak-cargo-home"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre.workspace = true
eyre.workspace = true
futures.workspace = true
itertools.workspace = true
tokio.workspace = true
